### ISSUE TITLE
Regex does not show on invalid regex error.

### ISSUE THREAD

**Issue by Peashooter101** [ADHDMC/SimpleNicks#2]
# Problem

`/nick set <gradient:dark_green:green>`
`/nick set <gradient:dark_green:green>Peashooter101`

![image](https://user-images.githubusercontent.com/20095065/209594416-a918ebc2-66f0-439c-960a-94443ff9850a.png)

**Comment by RhythmicSys** [comment]
fixed a while back but I forgot to close the issue
